#!/usr/bin/python

"""
Simple rst2man like utility that fetches information from arc source code
to make it more automatically maintanable.
"""

import locale
try:
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description
from docutils.writers import manpage

from arc.version import VERSION

class Translator(manpage.Translator):
    def __init__(self, document):
        manpage.Translator.__init__(self, document)
        self._docinfo['version'] = VERSION


class Writer(manpage.Writer):
    def __init__(self):
        manpage.Writer.__init__(self)
        self.translator_class = Translator


description = "Generates ARC unix manual documents. %s" % default_description
publish_cmdline(writer=Writer(), description=description)
