#!/usr/bin/python

"""
Simple rst2man like utility that fetches information from arc source code
to make it more automatically maintanable.
"""

import os
import sys
import locale
try:
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline, default_description
from docutils.writers import manpage

THIS_FILE = os.path.abspath(__file__)
MAN_DIR = os.path.dirname(THIS_FILE)
ARC_DIR = os.path.dirname(MAN_DIR)

sys.path.insert(0, ARC_DIR)

from arc.version import VERSION
from cli_parser_extract import parser_to_rest_build_file
from cli_args_extract import module_name_to_rest_build_file

class Translator(manpage.Translator):
    def __init__(self, document):
        manpage.Translator.__init__(self, document)
        self._docinfo['version'] = VERSION


class Writer(manpage.Writer):
    def __init__(self):
        manpage.Writer.__init__(self)
        self.translator_class = Translator


if __name__ == '__main__':
    parser_to_rest_build_file()
    for command in ('host', 'job', 'label', 'test', 'server'):
        parser_to_rest_build_file(command)
        module_name_to_rest_build_file(command)

    description = ("Generates ARC unix manual documents. %s" %
                   default_description)
    publish_cmdline(writer=Writer(), description=description)
