#!/usr/bin/env python
#
# -*- Mode: Python; coding: iso-8859-1 -*-
# vi:si:et:sw=4:sts=4:ts=4

import logging
import arc.cli.app


#logging.basicConfig(level=logging.DEBUG)


def main():
    app = arc.cli.app.App()
    app.run()


if __name__ == '__main__':
    main()
