#!/usr/bin/python
#
# -*- Mode: Python; coding: iso-8859-1 -*-
# vi:si:et:sw=4:sts=4:ts=4

import os
import sys
import logging

# simple magic for using scripts within a source tree
basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if os.path.isdir(os.path.join(basedir, 'arc')):
    sys.path.append(basedir)

import arc.cli.app


def main():
    app = arc.cli.app.App()
    app.run()


if __name__ == '__main__':
    main()
